const TRUTH_STAGES=new Set(['predicted','verified','observed']);
const CAPABILITIES=['ai','vision','document','repository','persistence','observation','search','payments','geospatial','media','notifications'];
const uuid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
export const envKey=(c,s)=>`ELITE_${c.toUpperCase().replace(/[^A-Z0-9]/g,'_')}_${s}`;
export const capabilityStatus=(caps=CAPABILITIES)=>caps.map(capability=>({capability,configured:Boolean(process.env[envKey(capability,'ENDPOINT')]),authenticated:Boolean(process.env[envKey(capability,'TOKEN')])}));
export function createPortfolioContext(input={}){if(!input.tenantId?.trim())throw new Error('tenantId is required');if(!input.actorId?.trim())throw new Error('actorId is required');return{tenantId:input.tenantId,actorId:input.actorId,traceId:input.traceId||uuid(),requestId:input.requestId||uuid(),...(input.projectId?{projectId:input.projectId}:{}),...(input.opportunityId?{opportunityId:input.opportunityId}:{})}}
export function assertTenant(c,t){if(!t?.trim())throw new Error('expected tenant is required');if(!c?.tenantId||c.tenantId!==t)throw new Error('tenant boundary violation')}
export function portfolioHeaders(context={},token){if(!context.tenantId||!context.actorId)throw new Error('tenantId and actorId are required');return{'content-type':'application/json','x-elite-tenant':context.tenantId,'x-elite-actor':context.actorId,...(context.traceId?{'x-elite-trace':context.traceId}:{}),...(context.requestId?{'x-elite-request':context.requestId}:{}),...(context.projectId?{'x-elite-project':context.projectId}:{}),...(context.opportunityId?{'x-elite-opportunity':context.opportunityId}:{}),...(token?{authorization:`Bearer ${token}`}:{})}}
export function createPortfolioEvent({type,source='ELITE-ESTIMATING-',context,data,id,occurredAt}){if(!type?.trim())throw new Error('event type is required');if(!context?.tenantId||!context?.actorId)throw new Error('event context requires tenantId and actorId');return{specVersion:'elite.event.v1',id:id||uuid(),type,source,occurredAt:occurredAt||new Date().toISOString(),context,data}}
export function provenance(source,resolver,extra={}){if(!source||!resolver)throw new Error('provenance requires source and resolver');return{source,resolver,capturedAt:new Date().toISOString(),...extra}}
export function observation(name,truthStage,metadata={},context={}){if(!TRUTH_STAGES.has(truthStage))throw new Error(`invalid truth stage: ${truthStage}`);return{id:`${name}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name,truthStage,occurredAt:new Date().toISOString(),tenantId:context.tenantId,actorId:context.actorId,projectId:context.projectId,traceId:context.traceId,requestId:context.requestId,metadata}}
export async function callCapability(capability,payload,context={},options={}){const endpoint=process.env[envKey(capability,'ENDPOINT')];if(!endpoint)return{status:'unconfigured',capability,fallbackRequired:true};const url=new URL(endpoint);if(url.protocol!=='https:'&&url.hostname!=='127.0.0.1'&&url.hostname!=='localhost')throw new Error('capability endpoint must use HTTPS outside local development');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),options.timeoutMs??10000);try{const token=process.env[envKey(capability,'TOKEN')];const normalized=context.tenantId&&context.actorId?createPortfolioContext(context):context;const headers=normalized.tenantId&&normalized.actorId?portfolioHeaders(normalized,token):{'content-type':'application/json',...(token?{authorization:`Bearer ${token}`}:{})};const response=await fetch(url,{method:'POST',signal:controller.signal,headers,body:JSON.stringify(payload)});if(!response.ok)throw new Error(`${capability} provider returned ${response.status}`);return{status:'resolved',capability,data:await response.json(),context:normalized}}finally{clearTimeout(timeout)}}
export function releaseGate(checks){const failures=Object.entries(checks).filter(([,v])=>!v).map(([n])=>n);return{passed:failures.length===0,failures}}
export const eliteRuntime={truthStages:[...TRUTH_STAGES],capabilities:CAPABILITIES,portfolioEventSpec:'elite.event.v1'};
